# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

---

# image will be published to ghcr.io/<user>/<name>
name: koplos
# description will be included in the image's metadata
description: Bazzite-based image incorporating a modernized set of linux core utils featuring the fish shell

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # Copy any files into the appropriate system directories first
  - from-file: files.yaml
  # Install System Packages
  - from-file: dnf.yaml
  - from-file: eget.yaml
  - from-file: flatpaks.yaml

  # Install Configuration Management, Fonts, Services, etc.
  - from-file: chezmoi.yaml
  - from-file: fonts.yaml
  - from-file: systemd.yaml
  # Run any scripts/commands needed to finish up installation steps
  - from-file: espanso.yaml
  # Finishing Details
  - from-file: os-release.yaml
  # Image Signing
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
